"""locators.py"""

class WebLocators:
    username_locator = "user-name"
    password_locator = "password"
    login_locator = "login-button"
    err_mes_locator = "//button[@class='error-button']"
    menu_butn_locator = "react-burger-menu-btn"
    logout_locator = "logout_sidebar_link"
    cart_button = "shopping_cart_container"
    add_to_Cart_back_pack_locator = "add-to-cart-sauce-labs-backpack"
    add_to_cart_bike_light_locator = "add-to-cart-sauce-labs-bike-light"
    add_to_cart_t_shirt_locator = "add-to-cart-sauce-labs-bolt-t-shirt"
    add_to_cart_jacket_locator = "add-to-cart-sauce-labs-fleece-jacket"
    select_cart_locator = "shopping_cart_container"
    checkout_locator = "checkout"
    f_name_locator = "first-name"
    l_name_locator = "last-name"
    zip_c_locator = "postal-code"
    continue_locator = "continue"
    finish_locator = "finish"